services:
  postgres:
    image: postgres:latest
    container_name: pracainzynierska_db
    environment:
      POSTGRES_DB: pracainzynierska_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
